### ISSUE TITLE
Kibana deployment name vs Elasticsearch statefulset name.

### ISSUE THREAD

**Issue by jordansissel** [elastic/helm-charts#10]
For Elasticsearch, the statefulset name seems to follow `{clusterName}-{nodeGroup}`

Kibana's deployment, however, seems to be `kibana-kibana`. If I set `nameOverride` for Kibana, the deployment becomes `kibana-{nameOverride}`.

I kinda want to see things grouped by cluster name, and while Kibana has no such concept, I would wish for the kibana deployment to be called `{nameOverride}-kibana`.

Given this is a naming proposal, I'm almost willing to close it immediately myself because naming is hard and maybe nobody will like any one proposal ;)

Thoughts?

**Comment by Crazybus** [comment]
So the name comes from the [autogenerated templates](https://github.com/helm/helm/blob/e7bd4da6838f315459f57126a1667335b4058012/pkg/chartutil/create.go#L268-L300) from the `helm create` command. In other words it's not something that was thought about. 

I totally agree that it makes more sense to switch it around for our use case so that a `kubectl get pods` shows Elasticsearch and Kibana for the same cluster next to each other. 

👍 from me!
