### ISSUE TITLE
7.11.0 Charts

### ISSUE THREAD

**Issue by mcmarkj** [elastic/helm-charts#1059]
👋 Hello! 

Just checking what the timescales are for the 7.11.0 charts to be ready to coincide with the [release last night](https://www.elastic.co/blog/whats-new-elastic-7-11-0-searchable-snapshots-schema-on-read).

**Comment by ebuildy** [comment]
Hello, as usually with every new elasticsearch releases ^^ you can set imageTag to any version you want! (even snapshot).

**Comment by mcmarkj** [comment]
Am I mistaken, don't you usually create helm charts to match the version numbers of Elastic stack releases?

I intentionally inherit the imageTag from the Helm release version so they all move in parallel

**Comment by ebuildy** [comment]
nop, it's not a common practice, thats why Chart.yaml have "version" and "appVersion" (https://helm.sh/docs/topics/charts/).

**Comment by jmlrt** [comment]
Hi @mcmarkj, @ebuildy,

Despite not being a common practice in Helm, Elastic usually release new chart (`version`) with every stack release (`appVersion`) and officially support only chart version matching a stack version.

This is our way to ensure that charts are always properly tested and compatible with the last version from Elastic product.

However, using a specific chart version with a different stack version is usually fine when there is some specific need by overriding the `imageTag` parameter as incompatibilies are really rare, especially when using chart and product matching the same minor or major version.

We usually release charts in the same time as stack but may delay it a bit when we encounter complications with one or the others.

As for 7.11.0 chart release missing, we discovered some bug in Elasticsearch just after 7.11.0 release (https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.11.0.html#known-issues-7.11.0), which forced us to focus on releasing an emergency fix in 7.11.1 instead of working on charts 7.11.0 release.

We eventually decided to release directly 7.11.1 for charts and totally skip 7.11.0 as it wouldn't make sense to release both versions in the same time with 7.11.0 having a known bug fixed in 7.11.1.

**Comment by jmlrt** [comment]
[7.11.1](https://github.com/elastic/helm-charts/releases/tag/v7.11.1) is now released and is the good version to use.

**Comment by mcmarkj** [comment]
Thanks @jmlrt - I knew it wasn't common practice for Helm. Was convinced I had read here before that you liked to keep helm charts moving at the same time as the stack releases - hence my question and confusion around the conflicting message.

Really appreciate the new release - keep up the good work.
