### ISSUE TITLE
[Elasticsearch-OSS] Cannot Start using OSS version

### ISSUE THREAD

**Issue by ichasco-heytrade** [elastic/helm-charts#1085]
Hi, I am having an error when deploying elasticsearch-oss because is not compatible with `node.ml`. And the script force to add it.
The only way to run it is to edit manually the statefullset and delete:
```
containers:
      - env:
        - name: node.ml
          value: false,
 ```

It doesn't matter if I set it to false. It crash with this error:

```
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [node.ml] please check that any required plugins are installed, or check the breaking changes documentation for removed settings",
```

**Chart version:** 7.11.1

**Kubernetes version:** v1.18.9

**Kubernetes provider:** EKS

**Helm Version:** v3.5.0

**Elasticsearch Version:** 7.10.2

Thanks!

**Comment by xrl** [comment]
I had the same issue and I read over the templates a bit, looks like they take the entries from the release's role list and dynamically create ES config properties. The new default values include a `ml` and `remote_cluster_client` whose presence, true or false, would put an unsupported config in to my version of ES (`7.2.0` which I'm in the process of upgrading, hence this issue).

The fix? Don't let the helm template see any value for those two bad keys:

```
# snippet from my logs-master.yaml value file
roles:
  master: "true"
  ingest: "false"
  data: "false"
  ml:
  remote_cluster_client:
  ```

**Comment by ichasco-heytrade** [comment]
Thanks @xrl it seems to work like that! :)

**Comment by xrl** [comment]
Not positive this should be closed, this is a nasty bug for future users :)

**Comment by ichasco-heytrade** [comment]
Ok I will let it opened

**Comment by jmlrt** [comment]
Hi @ichasco-heytrade, @xrl,
Elastic charts provide default values and support when used with the same version for chart and application.
This is why the `roles` value is expected to work with Elasticsearch 7.11 but not necessarily with previous versions or OSS version which doesn't exist anymore in 7.11.

That's why we won't update the values and your workaround is the good to handle it on your side.

**Comment by xrl** [comment]
This chart says it supports the 6-series. At the very least it could be documented?

**Comment by jmlrt** [comment]
Indeed, that's why we have a different branch for [6.8](https://github.com/elastic/helm-charts/tree/6.8) which doesn't include `ml` and `remote_cluster_client` in default values + tags for every [releases](https://github.com/elastic/helm-charts/releases) and we specify [here](https://github.com/elastic/helm-charts#charts) that you should use an Helm chart version is aligned to the version of the product you want to deploy.

>We recommend that the Helm chart version is aligned to the version of the product you want to deploy. This will ensure that you using a chart version that has been tested against the corresponding production version. This will also ensure that the documentation and examples for the chart will work with the version of the product you are installing.
>
>For example if you want to deploy an Elasticsearch 7.7.1 cluster, use the corresponding 7.7.1 tag.

**Comment by jmlrt** [comment]
Hi @botzill,using Elasticsearch 8.0.0-SNAPSHOT with this chart is currently broken because of https://github.com/elastic/helm-charts/issues/855 and we have a wip PR to fix it: https://github.com/elastic/helm-charts/pull/1186

Please note that Elasticsearch 8.0.0-SNAPSHOT is an unsupported development version available only for tests.

The latest supported version is 7.12.1 for now.
