### ISSUE TITLE
support multiple master node groups

### ISSUE THREAD

**Issue by gbanasiak** [elastic/helm-charts#1268]
**Describe the feature:**

As a Helm Charts user I would like to have an option to specify multiple master node groups with different settings. Today, `cluster.initial_master_nodes` is set to a list of nodes from current node group instead of _all_ master nodes which is what is advised in [ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/modules-discovery-bootstrap-cluster.html)

> You must set `cluster.initial_master_nodes` to the same list of nodes on each node on which it is set in order to be sure that only a single cluster forms during bootstrapping and therefore to avoid the risk of data loss.

**Describe a specific use case for the feature:**

Let's assume a setup with 3 master/data nodes in 3 different AZs.

```
AZ1 :
master/data node (node attribute az:az1)

AZ2:
master/data node (node attribute az:az2)

AZ3:
master/data node (node attribute az:az3)
```

It's preferred to configure shard allocation awareness in such scenario:
```
cluster.routing.allocation.awareness.attributes: az
cluster.routing.allocation.awareness.force.zone.values: az1,az2,az3
```

To achieve this multiple node groups must be used but they do not work correctly with master node groups.

**Comment by PPACI** [comment]
I have the same issue.
To support this I came with a hack

I have 3 separated helm chart deployment that together form one cluster (with different AZ and zone awareness as author did).

My "AZ1" master group is set up without any workaround.
But then to make the cluster AZ2 to form a cluster with AZ1, I have to remove initial_master_nodes with the following.

```yaml
      extraEnvs:
        - name: cluster.initial_master_nodes
          value: ""
```
And the same for AZ3.

It works since Kubernetes takes the last occurence of a env variable. But still, in the final template, the variable cluster.initial_master_nodes is set twice and this cause issue when updating.

Being able to set cluster.initial_master_nodes to an arbitrary value (even an empty string) would be perfect. I think it could be achieved by using the tpl function from helm and using the current value `"{{ template "elasticsearch.endpoints" . }}"` as default in helm.

I also have the exact same problem with  

```yaml
            - name: discovery.seed_hosts
              value: "{{ template "elasticsearch.masterService" . }}-headless"
```

Transforming it to 

```yaml
            - name: discovery.seed_hosts
              value: "{{ tpl .value.seed_hosts }}"
```

The default values of `seed_hosts` being `"{{ template "elasticsearch.masterService" . }}-headless"`.

That would help a lot people creating multiple AZ cluster in multiple Helm deployment.

I think I'll soon fork this chart to support my use case, but it would be pretty cool to see it (or an equivalent features) in the official chart.

**Comment by PPACI** [comment]
Update on my side.
We've done a fork of this chart.
I can pass cluster.initial_master_nodes manually, it will default to templated value if I do not set anything.
I can open a Pull Request if needed.

**Comment by PPACI** [comment]
I'll soon introduce a PR with the minimum change to make this possible.
