### ISSUE TITLE
[elasticsearch] Support security initialization (X-Pack)

### ISSUE THREAD

**Issue by tgruenert** [elastic/helm-charts#159]
## Feature 
Beginning with ElasticSearch 7 X-Pack basic includes security features. 
ElasticSearch helm chart should support initial setup of Certificates across multinode enviroment.

## UseCase 
1) As a cluster owner i need to setup up a new cluster with 1, 3 or more master-nodes and enable securtiy feature for user management. This requires TLS between my elasticsearch nodes.
Helm chart (or/and init container) should generate and install all required certificates. 
Certifactes and generated passwords may can be written in a given mount point.

2) As a cluster owner i would re-install a cluster with existing certifactes and users. 

If i overloocked this feature or parts of this right now any notes are welcome.

**Comment by Crazybus** [comment]
Did you already take a look at the docs for setting up a [security enabled cluster](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md#security)? For now this is the recommended way to do it. 

In theory it would be possible to automate all of this within the helm chart and do everything inside the Kubernetes cluster. However it would require firing off a job to generate the certificates which would also automatically create the Kubernetes secrets needed to mount them. This means it isn't as simple as adding an init container because the certificates need to be shared between all of the pods in the statefulset. 

I have been meaning to update the security example to autogenerated certificates if they don't exist (instead of pulling from vault) which is the final step needed to close #27

**Comment by tgruenert** [comment]
I am a little confused about the [first step](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/configuring-tls.html#node-certificates) within the helm chart guide.
How should i use elastic tools without a running elasticsearch? Kubernetes does not give me a console without  working health check. Do i missed something completely?

**Comment by userguy** [comment]
@tgruenert What you have to do is download tar and run the ca command to generate stack certificate and then you have to use that to generate certificate . In short your certificate can be setup independent . You just need certificate and elastic-search documents the setup

**Comment by tgruenert** [comment]
@userguy thank you for clarifying this. I will try this next time.

**Comment by Crazybus** [comment]
For what its worth the updated security example now runs the certificate generation inside of a docker container:

https://github.com/elastic/helm-charts/blob/adc17bca05906e4c3de10ffa9f32f47058b40322/elasticsearch/examples/security/Makefile#L16-L31

**Comment by jgato** [comment]
Sorry I think this is what I need. An automatic way of creating certificates when I deploy the ES cluster. Please, would you give more details how to do use that makefile?

**Comment by yaphetsglhf** [comment]
just run `make secrets`

**Comment by harsh4870** [comment]
When generating certs and adding into cluster it's only working with `curl --insecure` mode HTTPS protocol. i am not sure web server or web client would be able to query ES than. 

Is there anything i am missing? i have not expose my ES cluster it's running internally inside K8s.

**Comment by MykolaPelyp-SoftServe** [comment]
Something is wrong with your script, when running ```make secrets``` inside the examples/security directory I am getting: (last 4 strings of the error)
```
configure the client to trust this certificate.
elastic-helm-charts-certs
The connection to the server localhost:8080 was refused - did you specify the right host or port?
make: *** [Makefile:24: secrets] Error 1
```

**Comment by harsh4870** [comment]
@MykolaPelyp-SoftServe  https://discuss.kubernetes.io/t/the-connection-to-the-server-localhost-8080-was-refused-did-you-specify-the-right-host-or-port/1464/4
