### ISSUE TITLE
[kibana] Import dashboard

### ISSUE THREAD

**Issue by naseemkullah** [elastic/helm-charts#165]
**Describe the feature:**
Import dashboard on container creation.

**Describe a specific use case for the feature:**
To import saved objects.

As per: https://github.com/helm/charts/blob/0dc8468615aa0b23795e07178dfb330fe466e532/stable/kibana/values.yaml#L152-L163

**Comment by Crazybus** [comment]
Seems like a cool feature. A few questions just so I'm sure I understand correctly.

1. Is this so that you have an easy way to install the same dashboard into multiple Kibana instances? Or is there another use case for wanting this.
2. How does this work during the initial deploy of Kibana? In the chart you linked to this is running as an initContainer so this will run before Kibana has been actually deployed. 

Random other note for future reference: It seems that this implementation requires putting the username and password into the values.yaml. Instead it would make more sense to use something similar to what the [readinessProbe does](https://github.com/elastic/helm-charts/blob/4cef518903fe7a9d8624967a06b6c0e799d0d93a/kibana/templates/deployment.yaml#L85-L97) to make sure these secrets aren't exposed.

**Comment by naseemkullah** [comment]
Hi @Crazybus ,
 1. Is correct. Furthermore, by importing a dashboard, I also import it's child saved objects notably index-pattern. This index-pattern has a consistent ID, that one that is in the dashboard json that is being imported. This really comes in handy for me.
2. That's correct, as per the referenced chart.

I agree, personally I do not use x-pack so that did not affect me. Maybe we can start by implementing as is then follow up with an issue to obscure the xpack credentials.
