### ISSUE TITLE
[elasticsearch] 3 data nodes but only 2 are used ?

### ISSUE THREAD

**Issue by naseemkullah** [elastic/helm-charts#175]
Default values give us 3 multi role nodes, but we are wasting storage by mounting a big PVC on 3 nodes when only 2 of them seem to be used. What's the best workaround for this? Deploy seperate charts for the different components?

**Comment by naseemkullah** [comment]
BTW my impression is that only 2 are used because indices tend to have a replicas value of 1 by default

**Comment by Crazybus** [comment]
The default values includes 3 nodes because this is the bare minimum needed to run a production ready Elasticsearch cluster. Running with only 2 master nodes sets you up for split brain scenarios. In the [getting started](https://github.com/elastic/helm-charts/tree/master/elasticsearch#usage-notes-and-getting-started) section of the readme there is a note about how to deploy a cluster with multiple dedicated node types (e.g. 3 masters and 2 data nodes if you wanted). 

> BTW my impression is that only 2 are used because indices tend to have a replicas value of 1 by default

This is indeed true if you only have 1 index in your cluster and you have 3 data nodes. If you have more than 1 index with 1 replica then they will be evenly spread across all available nodes.

If your use case is that you have 1 index and you only want 1 replica then deploying 2 dedicated data nodes is the way to go with a values.yaml like this:

```
replicas: 2

nodeGroup: "data"

roles:
  master: "false"
  ingest: "true"
  data: "true"
```

**Comment by naseemkullah** [comment]
Thanks for the detailed explanation @Crazybus! 

I actually keep at least 7 indices (7 days worth of data aka logtsash-<DAY>), and that may continue to grow, so I am happy to learn these will be evenly spread out across the 3 data nodes.
