### ISSUE TITLE
UPGRADE FAILED: timed out waiting for the condition

### ISSUE THREAD

**Issue by mounaBoo** [elastic/helm-charts#209]
Hello, 
I am trying to install the  elastic helm chart with security enabled 

I did everything recommanded to , elasticsearch is installed correctly without problem
but once I upgrade Kibana with the security.yml provided it shows me this error : 

```
UPGRADE FAILED
Error: timed out waiting for the condition
Error: UPGRADE FAILED: timed out waiting for the condition
```

I run the Makfile provided but the same error appear I used this command : 

the same error occured : 
` helm upgrade --wait --timeout=600 --install --values ./security.yml kibana ../../ --debug`

can any one help me with this issue I have been trying to upgrad it to the security always failing with the same problem.

**Comment by Crazybus** [comment]
I'm going to close this since its a duplicate of the discussions we are having in https://github.com/elastic/helm-charts/pull/205. This PR adds automation for automatically generating the certificates. If you are still unable to get it working with the new changes we can re-open this issue and continue to work on it.
