### ISSUE TITLE
Offical Elastic-Stack Chart

### ISSUE THREAD

**Issue by james-crowley** [elastic/helm-charts#221]
**Describe the feature:**
It seems like everyone here is slow porting over the charts from https://github.com/helm/charts. I can see you guys plan support for Logstash, #69 , but are you going to support an Elasitc-Stack Chart the brings all the charts together? I am mostly talking about porting over the functionality of https://github.com/helm/charts/tree/master/stable/elastic-stack. 

**Describe a specific use case for the feature:**
It would be amazing to have the updated charts, 7.X, and have them all be able to deploy in easy to use fashion.

**Comment by Crazybus** [comment]
> It would be amazing to have the updated charts, 7.X, and have them all be able to deploy in easy to use fashion.

Yes it would, however this would also need to happen in a proper fashion. Can you explain how you follow the [proper upgrade order](https://www.elastic.co/guide/en/elastic-stack/current/upgrading-elastic-stack.html#upgrade-order-elastic-stack) with the current stack chart? It seems like you would need to first update only the Elasticsearch version, wait for it to upgrade, then update the Kibana version...wait...then do this for the rest of the sub charts. Where this gets tricky is how to handle upgrades to new chart versions that might be needed to support a specific application version. At this point it seems like it would just be easier to manage each of them as separate releases. 

The second tricky part is that it locks you into a specific architecture. The advantage of having each group of Elasticsearch nodes deployed in separate releases is that you can define and redefine your architecture at any stage. It also makes it possible to do blue/green style deploys if you want to resize the storage for some nodes in a Kubernetes cluster that doesn't support disk resizing. I guess nothing is stopping you from just deploying a new release with a new node group though. 

Are there any advantages that I might be missing? It actually sounds like more work to upgrade/maintain then just managing the releases separately. Internally we are using the [terraform helm provider](https://www.terraform.io/docs/providers/helm/release.html) which allows us to manage the dependencies between each part of the stack. This allows you to define things like "Upgrade Elasticsearch first, wait for it to be done, then do Kibana".

**Comment by james-crowley** [comment]
@Crazybus 

I am not sure how migration would happen. I did see that the existing Helm Charts started to put out migration guides, [here](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/migration/README.md).


I am not sure I follow your second point. How does it lock you into a specific architecture? That is kind of how all the Helm Charts operate right now. Someone defines a template of how a general architecture should look and you can utilize that chart. If not, you could modify it to your liking. With the current stack chart, they do allow a couple options of modifying the architecture to your liking, but it is still overall “fixed” like the other Charts. But I do agree that deploying charts for the Elastic stack would allow more modularity.

I think having a stack chart would benefit the community. There is obviously a want/need for this chart, or else it would not have been maintained/utilized by the community.

One thing I love about it is it’s a quick and easy way to get up an elastic stack environment. Especially when clients are looking into Elastic but need to try it out before dropping money on hardware or software licenses.

I am sure other members in the community also have their reasons as well.

**Comment by Crazybus** [comment]
> I am not sure how migration would happen. I did see that the existing Helm Charts started to put out migration guides, here.

Let me try re-wording things. I didn't mean the migration from one chart to another. I'm talking about the concept of using a multi chart to deploy the stack. When upgrading components of the Elastic stack there is a very important order that things must be done in that is [documented here](https://www.elastic.co/guide/en/elastic-stack/current/upgrading-elastic-stack.html#upgrade-order-elastic-stack). If you manage all parts of the stack with a single "stack chart" you lose the ability to upgrade components in the correct order. 

If you do upgrade Kibana and Elasticsearch at exactly the same time (what a stack chart would do) Kibana will fail to startup because the current version of Elasticsearch is older than the Kibana version. This means that Kibana will be unavailable until the upgrade has finished. This is also true for any logging or metrics that might be coming from filebeat/metricbeat/logstash. 

You can work around this by manually managing each version of the stack within the stack chart and bumping them one by one. However the complexity comes in from the fact that you need to update the stack chart version first, then each of the individual application versions. This becomes even harder during a major version upgrade where there may be breaking changes. And in the end this is the same amount of work as using separate releases but just with less flexibility. 

> I think having a stack chart would benefit the community. There is obviously a want/need for this chart, or else it would not have been maintained/utilized by the community.
> One thing I love about it is it’s a quick and easy way to get up an elastic stack environment. Especially when clients are looking into Elastic but need to try it out before dropping money on hardware or software licenses.

I certainly agree that a stack chart is "quick and easy". And I'm certainly not arguing that there isn't demand for it. It's very important to me that users of these charts have a good experience, and that the by default get something that is production ready and follows best practices. If my understanding around the upgrade order issues is correct then a stack chart would be setting up our users to have a bad experience using the stack. I wouldn't be comfortable adding a chart that directly goes against our best practices that would cause downtime every-time someone does an upgrade. 

To offer a stack chart we would need to have a way to properly solve the upgrade order problem. If there is a way to do that with a stack chart then I'm totally for this!

**Comment by james-crowley** [comment]
@christian-roggia, @yurinnick and @rendhalver care to weigh in, as it looks like you are the maintainers of the Elastic-Stack Chart? Maybe you guys have more knowledge on how the Chart was setup and maintained in the past.

**Comment by rendhalver** [comment]
We have been using the elastic helm charts to deploy out Elasticsearch clusters since about January this year.
I can vouch for the multi-chart setup. It works well.
We use a version of the approach from #22 internally and the stable/elastic-stack for the rest.
Having one meta-chart to install the whole stack was something we wanted from the start and wrote stable/elastic-stack to try and achieve that.
As you are all probably aware just about everything in that chart is optional so the "one chart fits all uses" obviously isn't easily achieved and it might be something each organisation needs to look after themselves.
That said I am happy to help out porting it here so it's part of the family.
Give me a bit to catch up on the conversation and add comments and ideas if I have them.

**Comment by james-crowley** [comment]
@rendhalver Thanks for the input. It helps to have a person who has an in depth knowledge on the chart contribute to this conversation. 

@Crazybus It still seems like the community wants this chart. Will Elastic be willing to work with us on maintaining this chart or should be be looking at hosting it over at https://github.com/helm/charts ?

I understand that there still needs a lot to be discussed/worked out, but I want to know if Elastic is willing to support this chart.

**Comment by Crazybus** [comment]
> To offer a stack chart we would need to have a way to properly solve the [upgrade order](https://www.elastic.co/guide/en/elastic-stack/current/upgrading-elastic-stack.html#upgrade-order-elastic-stack) problem. If there is a way to do that with a stack chart then I'm totally for this!

If there is a way to solve this then I'm all up for supporting it! However as I have already stated it appears that the current stack chart does not solve this problem and goes against very important best practices for managing and upgrading the stack.
