### ISSUE TITLE
[elasticsearch] Provide a way to add index templates / mappings once Elasticsearch is up

### ISSUE THREAD

**Issue by davestephens** [elastic/helm-charts#249]
**Describe the feature:**
Provide a way to load index templates, mappings etc once elasticsearch is up.

**Describe a specific use case for the feature:**
To allow things like setting a default index template, ILM, mappings etc etc.

Apologies if there's already an accepted way to do this, I couldn't find anything obvious...

**Comment by Crazybus** [comment]
> To allow things like setting a default index template, ILM, mappings etc etc.

Could you explain in more detail about why you want to manage this within the Elasticsearch chart?

It's normally expected that whatever is sending the data to Elasticsearch is the one that manages the index template, ILM and mappings with [filebeat](https://www.elastic.co/guide/en/beats/filebeat/7.3/ilm.html) being a good example. The advantage of doing it this way is that it makes keeping the changes in sync easier and its one less thing for you to manage. Another alternative would be that whatever process is deploying the helm chart should also deploy and manage these settings too.

If you really want to manage these settings from within the Elasticsearch containers you could add as a `lifecycle.postStart` hook as I suggested in https://github.com/elastic/helm-charts/issues/236 (which also contains an example of configuring filebeat to manage ILM). However the lifecycle hook is quite a hacky solution where you won't get any feedback on if it worked or not.

**Comment by davestephens** [comment]
My issue consists of two parts, hopefully I can explain clearly ;-)

Firstly I don't want my application to have to consider the Elasticsearch infrastructure that it's connecting to, specifically how many shards, the lifecycle of indexes etc. It should just be provided with a URL hit - not worry if it's creating the right amount of shards for the infrastructure that Elasticsearch is running on. For example; if my cluster has 4 nodes, then anything more than 2x primaries and 1 replica of each (total 4 shards), would be a waste of time. It should be down to the creator/admin of the cluster to decide these settings, not an app dev (sadly typically not the same people!). I'd usually attack this type of issue by applying an index template that applies to `*`, and specifying X shards with X replicas - and so wanted to apply this with the Helm chart, if possible.

The other issue is index mappings, and this most certainly should live in the application - your point RE Filebeat makes complete sense and is what I'll do.

**Comment by Crazybus** [comment]
> Firstly I don't want my application to have to consider the Elasticsearch infrastructure that it's connecting to, specifically how many shards, the lifecycle of indexes etc. It should just be provided with a URL hit - not worry if it's creating the right amount of shards for the infrastructure that Elasticsearch is running on. For example; if my cluster has 4 nodes, then anything more than 2x primaries and 1 replica of each (total 4 shards), would be a waste of time. It should be down to the creator/admin of the cluster to decide these settings, not an app dev (sadly typically not the same people!). I'd usually attack this type of issue by applying an index template that applies to *, and specifying X shards with X replicas - and so wanted to apply this with the Helm chart, if possible.

All use cases are different, but in general shard count is something you should be basing off the type of data and its use case instead of the exact node count. From a creator/admin point of view your setup is optimised for high availability but those extra shards add more overhead. Starting from Elasticsearch 7 the default `index.number_of_shards` was changed from `5` down to `1` because of this. This [article](https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster) goes into more detail about ideas for how best to optimize your shard count. 

How do you currently deploy the helm chart release itself? Whatever automation is deploying the helm release is the ideal place to also set cluster wide settings (what we do internally). This gives you full control over when changes are actually deployed as well as making sure you get proper feedback if something fails (without it preventing your Elasticsearch cluster from running). 

---

Ignoring your specific use cases I do think there is value in having a way to have a script run after cluster changes have been deployed. There are certain cluster settings that are not application specific which you might want to set. I think creating a generic script that gets run as a [helm post-install hook](https://github.com/helm/helm/blob/master/docs/charts_hooks.md#writing-a-hook) would work. As this would solve the problem of not being blocking, having a way to detect failures and making sure that it runs after the cluster is healthy and deployed. 


I'm imagining something like this which would run in a `job` resource with all of the environment variables and mounts from the main Elasticsearch statefulset. 

```
postInstallScript: |
  #!/bin/bash
  set -euo pipefail
  curl -s --fail -XPUT -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD} '{{ .Values.protocol }}://{{ template "masterService" . }}:{{ .Values.httpPort }}/_license' -H "Content-Type: application/json" -d @/usr/share/elasticsearch/config/license/license.json
  curl -s --fail -XPUT -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD} '{{ .Values.protocol }}://{{ template "masterService" . }}:{{ .Values.httpPort }}/_all/_settings' -H "Content-Type: application/json" -d '{"settings": {"index.unassigned.node_left.delayed_timeout": "5m"}}'
```

**Comment by davestephens** [comment]
> How do you currently deploy the helm chart release itself? Whatever automation is deploying the helm release is the ideal place to also set cluster wide settings (what we do internally). This gives you full control over when changes are actually deployed as well as making sure you get proper feedback if something fails (without it preventing your Elasticsearch cluster from running).

For local dev I'm using https://github.com/garden-io/garden/ - I'm building an additional config image with various bits of json I want to fire into Elasticsearch once it's up. That is deployed as a k8s job, similar to how you describe above. 

A post-install script would be perfect! :+1:
