### ISSUE TITLE
Additional java opts 

### ISSUE THREAD

**Issue by pjaak** [elastic/helm-charts#260]
**Chart version:**
elasticsearch-7.3.0

**Kubernetes version:**
1.12.7

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
AWS

**Helm Version:**
2.13.1

**Describe the bug:**
So i am getting an error setting the esJavaOpts in the values of the chart. I am trying to change the garbage collection to XX:+UseG1GC. However i get the error, Multiple garbage collectors selected. Its like the ES_JAVA_OPTS is not being read correctly, or I am doing something wrong.

**Provide logs and/or server output (if relevant):**
Multiple garbage collectors selected

**Any additional context:**
Also this is my value for esJavaOpts:

esJavaOpts: "-Djava.net.preferIPv4Stack=true -Xmx6144m -Xms6144m -XX:+UseG1GC -XX:-UseConcMarkSweepGC -XX:-UseCMSInitiatingOccupancyOnly"

**Comment by Crazybus** [comment]
You are getting errors because that option is already set in the [default jvm.options](https://github.com/elastic/elasticsearch/blob/master/distribution/src/config/jvm.options) file which exists already inside the docker image. Any command line options specified via `esJavaOpts` will normally override those found in jvm.options hoever since this is a "different" options it looks like it conflicts instead. Could you try setting them in the `jvm.options` file like this: 

```
esConfig:
  jvm.options: |
    -Djava.net.preferIPv4Stack=true
    -Xmx6144m
    -Xms6144m
    -XX:+UseG1GC
```

**Comment by pjaak** [comment]
Hi @Crazybus,

This fixed the issue, thankyou for the help!

**Comment by slavniyteo** [comment]
As said in the [default jvm.options](https://github.com/elastic/elasticsearch/blob/master/distribution/src/config/jvm.options#L29):

> \## All settings below this section are considered
> \## expert settings. Don't tamper with them unless
> \## you understand what you are doing

And when you add following to your `values.yaml`:
```yaml
esConfig:
  jvm.options: |
    -Djava.net.preferIPv4Stack=true
    -Xmx6144m
    -Xms6144m
    -XX:+UseG1GC
```
you remove all the *expert* settings that have been set by default, because it overrides the default `jvm.options` file.

As for me, It would be better to copy the whole devault `jvm.options` to your values.yaml.

---

I'm not the one who develops this chart or Elasticsearch
Please correct me if I am mistaken.

**Comment by Crazybus** [comment]
> As for me, It would be better to copy the whole devault jvm.options to your values.yaml.

This is correct! Sorry for leaving that out of my original reply. Setting esConfig.jvm.options will fully override the default file.
