### ISSUE TITLE
Is podManagementPolicy:OrderedReady supported?

### ISSUE THREAD

**Issue by tallaxes** [elastic/helm-charts#35]
Including `podManagementPolicy` in values.yaml makes it seem like it may be, but I am not sure it would work, with the way readiness probes are used. Could you please clarify this? (Maybe also in the docs ...)

**Comment by Crazybus** [comment]
Hi @tallaxes!

Setting `podManagementPolicy: OrderedReady` will work for any node groups that are not bootstrapping the cluster. If you set it in for the `data` nodes group in the [multi example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/multi/data.yml) then it will work. 

Out of interest, what is your motivation for wanting to use this instead of the default?

**Comment by tallaxes** [comment]
Thank you for clarification, makes sense. No particular reason for `OrderedReady`, just trying to make sure I understand the range of scenarios/options that would work with your approach to readiness probes.

Also looking at the differences between these and other existing ES Helm charts - and  gradually realizing the benefits of your approach. Many of those implicitly use `OrderedReady`, so it is good to know that if anybody wanted to adopt your readiness probes, it would also necessitate switching to `Parallel`, at least on masters.

**Comment by Crazybus** [comment]
Thanks for the explanation!

I'm going to closed this since it seems like your question has been answered. Feel free to reopen if you have more questions though.
