### ISSUE TITLE
Control plane availability impacts data plane availability

### ISSUE THREAD

**Issue by erik-stephens** [elastic/helm-charts#376]
**Chart version:**

7.2.0

**Kubernetes version:**

1.15

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

on-prem

**Helm Version:**

2.15

**Describe the bug:**

Pods should remain ready even though masters not responding in a timely manner.

**Steps to reproduce:**

1. Create a 3-node master-only StatefulSet and a 1-node data-only StatefulSet.  Calling the cluster "foo":
1. `kubectl scale statefulset foo-master --replicas=1`
1. Wait for data node to become unready: `kubectl get pod foo-data-0 -w`
1. `kubectl get service foo-data | grep Endpoints`
1. `kubectl exec foo-data-0 -- curl -s --fail http://localhost:9200/`

**Expected behavior:**

Pod to remain in ready state, perhaps by using `/_cluster/health?local=true` instead of `/`.

**Provide logs and/or server output (if relevant):**
```bash
# k describe pod t1-data-0 | tail -n1
  Warning  Unhealthy  33s (x90 over 30m)  kubelet, r7c6n3  Readiness probe failed: Elasticsearch is already running, lets check the node is healthy

# k exec t1-data-0 -- curl -s --fail http://localhost:9200/
command terminated with exit code 22

# k exec t1-data-0 -- curl -s --fail http://localhost:9200/_cluster/health?local=true | jq .
{
  "cluster_name": "t1",
  "status": "red",
  "timed_out": false,
  "number_of_nodes": 3,
  "number_of_data_nodes": 1,
  "active_primary_shards": 0,
  "active_shards": 0,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": "NaN"
}
```

**Any additional context:**

Elasticsearch 6.8.1

https://github.com/elastic/helm-charts/blob/0411010e8f03c25c06d864ce62f5b482b5439bdb/elasticsearch/templates/statefulset.yaml#L215

Even with `masterTerminationFix: true`, master election takes quite a while (~60s).  I think it's timing out trying to publish cluster state to the just-left master, but that's another issue.  I mention cuz the net effect is that the Service can become unavailable (no ready Endpoints) and then it can take a while (3x successful health checks at 10s apart) to become ready again.

I'm happy to submit a PR but wanted to get your thoughts first.  Thanks!

**Comment by fatmcgav** [comment]
@erik-stephens The behaviour you've described is in-line with how we would expect Elasticsearch to behave in this scenario. 

I just wanted to clarify the behavior of the `readinessProbe` quickly. 
By default, once all the nodes have started and the cluster returns a `green` health, then any future readiness probe checks will only look at the availability of the local node, as you've identified above with the `http "/"` check.

So the fact that the `http "/"` check is failing when no masters are available is, I suspect, by design as without master nodes available there is very little that data nodes can actually do. 

Checking the `/_cluster/health?local=true` endpoint also wouldn't necessarily help  in this scenario; Whilst the node might still be "ready" from a k8s pov, again the actual actions that could be performed by this data node are going to be extremely limited due to the lack of any available master nodes. 

With regards to the time it takes to elect a new master and the `Service` to start responding again; we'd expect setting `masterTerminationFix: true` should have improved that behaviour... 
Would it be possible for you to gather some logs etc so we can confirm?
* `kubectl get events`
* `kubectl logs -l app=elasticsearch`

**Comment by fatmcgav** [comment]
@erik-stephens It's also worth noting that the behaviour of the `/` endpoint when there are no master nodes available has changed in `7.x` releases of Elasticsearch. See https://github.com/elastic/elasticsearch/pull/29045 for more info, but basically the `/` endpoint will return a `200` response even if there are no masters available. 

However the actions that the data nodes can perform in this scenario are still extremely limited. 
Any search requests are likely to return stale data, and any indexing actions will fail due to there being no master nodes available.

**Comment by erik-stephens** [comment]
> Any search requests are likely to return stale data, and any indexing actions will fail due to there being no master nodes available.

That's not my understanding and not what we're seeing in the wild.  I'm not 100% sure so I'll need to perform some tests before I can say with certitude.

> Any search requests are likely to return stale data, and any indexing actions will fail due to there being no master nodes available.

Assuming true, another side-effect is that the Service can end up with no Endpoints and leave us blind during a critical time, like when the cluster isn't healthy.  We could use the headless version of the service but that has the trade-off of sending requests to unready/non-existent pods.

Feel free to close if working as designed.  Our forked version swapped `/` for `/_cluster/health?local=true` in case that's of any interest to anyone.  Thanks for looking.

**Comment by fatmcgav** [comment]
> That's not my understanding and not what we're seeing in the wild.

We'd certainly be interested in any evidence of this behaviour :) 

> another side-effect is that the Service can end up with no Endpoints and leave us blind during a critical time

This is technically true. However a set of data nodes with no master nodes won't be able to tell you anything about why the master nodes are no longer accessible. This is where Kubernetes will however provide you with the required information... 

I guess I'm failing to see a scenario where having the data nodes still accessible without the master nodes would be useful. 

One other thing I've just thought of - As this is an Elasticsearch 6.8.1 cluster, when scaling down the `master` statefuleset, did you update the `discovery.zen.minimum_master_nodes` config to reflect the new number of masters?
As by [default](https://github.com/elastic/helm-charts/blob/0411010e8f03c25c06d864ce62f5b482b5439bdb/elasticsearch/values.yaml#L17), this value is set to `2` within the chart, so dropping below this number of master nodes would result in the cluster being unable to elect a new master... 
So this would then result in the data nodes not being able to connect to the master and effectively erroring out...

**Comment by erik-stephens** [comment]
Scaling the masters to 1 was only to reproduce - rolling the masters, which should be a relative non-event, is what is causing the non-headless Service to have no Endpoints which causes metrics collection to go blind.  Perhaps the solution is to use the headless service.

**Comment by fatmcgav** [comment]
> rolling the masters, which should be a relative non-event

Indeed it should, as this is how k8s handles upgrades, config changes etc... 

I was able to replicate a similar scenario in a cluster I've just set-up using `6.8.1` with 3 master and 2 data nodes.
Deleting a non-active master pod doesn't cause any change to the services status, however deleting the active master can result in a change to the service endpoints if the time it takes for the master election to complete exceeds the readiness probe configuration for `failureThreshold * (periodSeconds + timeoutSeconds)` - by default `3*(10+5)` or `~45` seconds.

I was able to mitigate this behaviour in my test cluster by increasing the `readinessProbe.failureThreshold` value configured on the `data` nodes.
```yaml
readinessProbe:
  failureThreshold: 10
```
This allows `~150` seconds for the master election to complete.

Are you able to give that a try and see if that mitigates the behaviour for you?

**Comment by godber** [comment]
> I guess I'm failing to see a scenario where having the data nodes still accessible without the master nodes would be useful.

If data nodes were still accessible indexing and searching could continue even with masters unavailable or during master election.

**Comment by fatmcgav** [comment]
> If data nodes were still accessible indexing and searching could continue even with masters unavailable or during master election

That's not strictly true... Search requests might work for cached requests, however the results would be stale.
And any index requests would fail with no master nodes available...
