### ISSUE TITLE
Why `masterService` in values.yaml ?

### ISSUE THREAD

**Issue by hachh** [elastic/helm-charts#43]
Hi all,

I read how this chart works and I don't understand why is there `masterService` in values.yaml.
Because service is defined with `{{ template "uname" . }}-headless` which is exactly the concatenation of clusterName  and nodeGroup  `{{ .Values.clusterName }}-{{ .Values.nodeGroup }}`.

In helpers : 
```
{{- define "uname" -}}
{{ .Values.clusterName }}-{{ .Values.nodeGroup }}
{{- end -}}
```

In service.yaml : 
```
kind: Service
apiVersion: v1
metadata:
  name: {{ template "uname" . }}-headless
```

But in statefulset.yaml : 
```
          - name: discovery.zen.ping.unicast.hosts
            value: "{{ .Values.masterService }}-headless"
```

**Comment by Crazybus** [comment]
Hi!

This value exists so that it is possible to build clusters with distinct groups of dedicated nodes. Rather than hardcoding how many masters or data or machine learning nodes you want, you instead deploy separate releases for each dedicated node type. This variable is used to connect the non-master nodes to the masters. 

If you take a look at the [multi](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/multi/) example you will see how this works. The first group of nodes is deployed with only the [master role](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/multi/master.yml) and the [data nodes](https://github.com/elastic/helm-charts/blob/3bb5b33ab0071774e715deb382a6e448bc6c6d07/elasticsearch/examples/multi/data.yml#L6) then have `masterService: "multi-master"` set so they know how to discover their masters. 

Does this make sense? It's explained in the readme in the [Clustering and Node Discovery](https://github.com/elastic/helm-charts/tree/master/elasticsearch#clustering-and-node-discovery) section too. If you have any suggestions for making the documentation better I'd love to hear it.

**Comment by Crazybus** [comment]
Feel free to reopen this issue if you still have questions.

An important note is that this no longer needs to be specified unless your using dedicated node groups and don't use `master` as the name of your master node group. https://github.com/elastic/helm-charts/pull/78
