### ISSUE TITLE
[elasticsearch] Use existing persistent volume claims

### ISSUE THREAD

**Issue by LucaPrete** [elastic/helm-charts#518]
I would be great if it could be possible to use an already existing PVC, as in the majority of the stable helm-charts.

AFAIK there's also an ongoing issue with the current way of using PVCs. Indeed, if elasticsearch gets removed and installed again, the new installation goes in error saying it's not able to mount the volume.

Is there any plan to implement this feature soon?

Thanks!

**Comment by james-choncholas** [comment]
Comment for activity

**Comment by jmlrt** [comment]
This make sense but we won't have time to work on it in short/mid-term.

**Comment by jmlrt** [comment]
Statefulsets don't allow currently to specify a name for PVC generated by `volumeClaimTemplates`.

Following [StackOverflow](https://stackoverflow.com/questions/46442238/can-i-rely-on-volumeclaimtemplates-naming-convention), PVC generated by `volumeClaimTemplates` seem to rely on `<Statefulset.volumeClaimTemplates.metadata.name>-<Statefulset.metadata.name>-<count>` convention

Elasticsearch chart define both `Statefulset.volumeClaimTemplates.metadata.name` and `Statefulset.metadata.name` values to `elasticsearch.uname` template.

https://github.com/elastic/helm-charts/blob/58bdd96312a08cf3e933ffa9afb3c7988c27dd80/elasticsearch/templates/_helpers.tpl#L18-L28 

If you create some PVC in advance following these naming convention (`elasticsearch-master-elasticsearch-master-0`, `elasticsearch-master-elasticsearch-master-1` and `elasticsearch-master-elasticsearch-master-2` with chart default values). These PVC will be re-used automatically. However, there is no way to use PVC following some other names.

**Comment by jmlrt** [comment]
closing as stale, doc should be added later in #894

**Comment by gsotiriou** [comment]
Hello. I am sorry to revive this but it has been a whole week of me banging my head against the wall not being able to find a concrete answer and scouring through issue threads. 

My scenario is the following:
- EKS Kubernetes cluster
- EFS (to avoid issues with pods in zone-a not finding volume in zone-b) StorageClass in place to opt for dynamic provisioning mode of PVCs
- Installing elasticsearch helm chart (replicas set to 1 for testing purposes keeping things simple). 
- First install creates the PVC as it should through the use of StorageClass and dynamic provisioning.
- Uninstalling the helm chart the PVC is Retained (either because the Reclaim policy has been set to retain in StorageClass or because that's how StatefulSet works in Kubernetes - not sure) 
- Reinstalling elasticsearch through helm second time (still replicas set to 1 / same StorageClass as well). 

Will/Should that Pod reuse the existing PVC? 
For my use case it's a requirement that it should - can I force it somehow? What would the steps be? 
Any help/guidance would be greatly appreciated!

**Comment by smrutimandal** [comment]
> 

Experienced this recently. Reinstalling the chart or deploying the same Elasticsearch (`kind: Elasticsearch`) manifest ignores the existing PVs and proceeds with creating new PVs and PVCs to use in the new statefulsets. Now I am stuck with two sets of volumes with data in both of them without a clue on how to merge them. 

Not fun!!

**Comment by smrutimandal** [comment]
> 
> Will/Should that Pod reuse the existing PVC? For my use case it's a requirement that it should - can I force it somehow? What would the steps be? Any help/guidance would be greatly appreciated!

Experienced this recently. Reinstalling the chart or deploying the same Elasticsearch (kind: Elasticsearch) manifest ignores the existing PVs and proceeds with creating new PVs and PVCs to use in the new statefulsets. Now I am stuck with two sets of volumes with data in both of them without a clue on how to merge them.

Not fun!!

**Comment by mhadidg** [comment]
I'm experiencing the same issue after destroying a previous deployment 🤦‍♂️ The behavior is quite unexpected.  I'm wondering if it would be possible to specify the exact name of the PVC as a workaround 🤔

```YAML
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
    ...
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        volumeName: pv-xxxxxxxxxxxxxxxxxx
        storageClassName: {storage-class-volume}
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 150Gi
```
