### ISSUE TITLE
ElasticSearch Data nodes with no persistence

### ISSUE THREAD

**Issue by jgato** [elastic/helm-charts#576]
Hi there,
I am deploying a cluster with two gruops:
 * First Groups for masters roles and two replicas
 * Second groups for data-ingest roles and 1 replica

The first group take volumes persistence from my default storage class. But the second one, the data role group no. Even if it is enabled persistence. Is this because data nodes dont need to persist?

**Comment by fatmcgav** [comment]
Hey @jgato. 

We generally recommend that questions such as this are asked on our Discuss forums at https://discuss.elastic.co/

However we have got an example [here](https://github.com/elastic/helm-charts/tree/7.6.2/elasticsearch/examples/multi) which deploys a `master` statefulset and a `data` statefulset. Maybe that will give you a clue as to what could be wrong with your configuration?

**Comment by jgato** [comment]
But this is not a ElasticSearch questions, is more related to the Helm-Chart to deploy ElasticSearch. These configurations I have followed and the result is: created volumes for master group but not for the others.  This is why my questions is that maybe is the correct way of working of your Helm package.

**Comment by fatmcgav** [comment]
@jgato I understand that your issue is related to deploying Elasticsearch using our official helm chart; however these Github issues are not actively monitored, whereas our Discuss forums are used by both our helm chart developers and also knowledgeable community members who are deploying Elasticsearch using the helm chart. 

That being said, are you able to provide the details from the "Bug request" template - https://github.com/elastic/helm-charts/issues/new?template=bug_report.md

Specifically, I'm interested in seeing the values files for both the master and data deployments, and a `helm get ...` for both.

**Comment by jgato** [comment]
Sorry for bothering... now it is creating also the Persistence for the data group :)

I have other questions but I will do it in your forum. Thanks
