### ISSUE TITLE
Elasticsearch on Kind does not work with kubectl 1.18.0

### ISSUE THREAD

**Issue by zoonage** [elastic/helm-charts#577]
**Chart version:**

Pulled directly from master`elasticsearch/examples/kubernetes-kind`

**Kubernetes version:**

kubectl client 1.18.0
```
# > kubectl version --client
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
```

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

N/A

**Helm Version:**

N/A

**`helm get release` output**

N/A

**Describe the bug:**

```
helm upgrade --wait --timeout=900 --install --values values.yaml helm-es-kind ../../
Error: invalid argument "900" for "--timeout" flag: time: missing unit in duration 900
make: *** [install] Error 1
```

`--timeout` needs a duration, so `900` should be `900s`

**Steps to reproduce:**

1. `cd elasticsearch/examples/kubernetes-kind`
2. `make install`

**Expected behavior:**

The Makfile should support the latest kubectl

**Comment by jmlrt** [comment]
Hi @zoonage,
`helm upgrade --wait --timeout=900 --install --values values.yaml helm-es-kind ../../` command is working fine with Helm 2.
I think you are using Helm 3 which is changing `--timeout` parameter to request a duration instead of an integer.

While we have #516 WIP PR to support Helm 3 which should fix this example and have already some good feedbacks about using Elasticsearch chart with Helm 3, it is important to notice that currently only Helm 2 is supported.

Can you confirm the Helm version you are using by posting the result of `helm version` command?

**Comment by zoonage** [comment]
Hi @jmlrt I am using Helm 3

```
#> helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

````

**Comment by jmlrt** [comment]
OK so having the Makefiles working with Helm 2 but not the Helm 3 is currently the expected behavior.
I'll close this issue then.
