### ISSUE TITLE
Metricbeat deployment doesn't allow to define `hostNetwork: true`

### ISSUE THREAD

**Issue by michaelhyatt** [elastic/helm-charts#774]
**Chart version:**
7.8.1

Metricbeat DaemonSet allows setting `hostNetwork: true`, but deployment doesn't support setting this option.

See the Metricbeat K8s manifest for deployment where this option can be specified:
https://github.com/elastic/beats/blob/master/deploy/kubernetes/metricbeat/metricbeat-deployment.yaml

**Comment by jmlrt** [comment]
Metricbeat daemonset is used to retrieve internal metrics from the node where it is running, which explains that it sometimes need to access the node host network to get these information (ie: real node name instead of pod name).

However, AFAIK, Metricbeat deployment is used instead to retrieve external metrics independently of the node where it is running (ie: query an external API like K8S cluster API). That's why it shouldn't need to access the node host network.

I don't see any case where Metricbeat deployment would need hostNetwork  that's why we didn't added this option.
