### ISSUE TITLE
Allow hostPath for data

### ISSUE THREAD

**Issue by micw** [elastic/helm-charts#83]
Hello,

we are running kubernetes on-premise where local storage is used. Unfortunately, auto-provisioning for local storage volumes is not yet available on kubernetes. It would be very useful if the chart supports "hostPath" as option alternatively to volumeClaimTemplate.

I added a similar feature to redis-ha a while ago: https://github.com/helm/charts/pull/11815

I you agree to this change, I'd create a PR for elastic.

Best regards,
Michael.

**Comment by Crazybus** [comment]
Hey Michael,

When using hostpaths how do you make sure that each pod is scheduled to the node with that pods data? My understanding is that this was the main reason that the local storage volumes was created to address. If there is some kind of trick to guarantee this then I would be open to the idea.

**Comment by micw** [comment]
@Crazybus In my deployments I use nodeSelector for this (e.g. tag all date nodes with elasticsearch/datanode=true and use this as selector).

**Comment by Crazybus** [comment]
> @Crazybus In my deployments I use nodeSelector for this (e.g. tag all date nodes with elasticsearch/datanode=true and use this as selector).

Could you give a bit more info since I still don't understand how that would work. This sounds like your pods could land on any of the data nodes that were tagged with `elasticsearch/datanode=true`. I'd like to understand how you can have 6 Kubernetes nodes and a 3 pod statefulset and keep the pods on the correct host which has their data. 

> Edit: actually hostPath is a workaround for a current limitation in K8S - it's just not possible to auto-provision local storage or hostPath volumes.

I was able to get local persistent volumes working with auto provisioning and have documented it in the [readme](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md#usage-notes-and-getting-started). This was on GCP so it probably wouldn't work for an on-prem cluster but it is indeed possible. 

I tested it following the [running the local volume static provisioner](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/local-ssd#example_local_pvs) for GKE.

**Comment by liquid-cloud** [comment]
Would love this feature!

**Comment by hjyoti** [comment]
Can any one explain how to use hostPath iun helm chart
